### PR TITLE
Add initial xvfb system dependency for OpenGL cores support in the cl…

### PR DESCRIPTION
**Pull request by sergystepanov**
…oud environment.

Related to #225.

### CODE REVIEW

**Comment by sergystepanov** [comment]
While testing n64 stuff, I noticed constant 2-3 sec audio hiccups, video stream seemed OK.

**Comment by giongto35** [comment]
Thank you very much. It's ok to have N64 work on WIndow unless you want to do it. Maybe Native Window has equivalent virtual monitor.
Theoretically, video should not output to monitor, I'm not sure about N64 implementation in Libretro. It makes the whole N64 implementation a bit hacky. We have a good workaround now btw.
Let me try testing the Audio, maybe the CPU is too high when running N64 that makes the Audio processing delay.

**Comment by sergystepanov** [comment]
@giongto35, as far as I know, it's not possible to render anything with the OpenGL backend without some window associated with its context. That's just how it was made. 
Both n64 Libretro emulators use OpenGL. It's possible that Vulkan API or DirectX backends don't require windows, idk, need to read.
Personally, I'm not a fan of xvfb since it doesn't support hw 3D rendering and primarily used for 2D rendering in clouds (browser page render and such). Not sure whether it would be useful to have 3D acceleration for clouds (do they have GPUs at all for a sane price?), but for own streamer I'm gonna try to go in that way anyway (:. Maybe, something like [this](https://virtualgl.org/About/Introduction).

About native Windows app n64 support: it's just a problem with my laptop GPU and drivers (Intel HD2000, HD3000). With any slightly modern GPU it will run without problems, I think. Native build for sure doesn't require X Windows. Windows has windows since version 1.0 (:
And btw, why you call Windows -- Window?

**Comment by giongto35** [comment]
Hi @sergystepanov ,
Interesting to know that. I wasn't aware of the 3d acceleration. You also provide information about virtual GL that will help me a lot later if I'm looking for optimization.
`And btw, why do you call Windows -- Window?`
: D And TIL Microsoft Window**s** with s.

Thank you very much. I learn many new things talking with you.

**Comment by giongto35** [comment]
@sergystepanov  the coordinator issue you mention is also valid I think but seems like we can spawn multiple Xvfb and forward to different port in case. :/

**Comment by sergystepanov** [comment]
@giongto35, about:
> @sergystepanov the coordinator issue you mention is also valid I think but seems like we can spawn multiple Xvfb and forward to a different port in case. :/

I thought about it a bit more and here is my theory (:
if we wanted to run multiple workers on the same machine, we could use just one xvfb-provided virtual display, because each worker instance creates its own OpenGL context including a separate rendering framebuffer for the emulator instance output.
And one fake display (in my PR it's just 1 px sized) is enough to allow of creating multiple fake windows during SDL's OpenGL context initialization since windows can overlap, stack, and whatever, also we aren't drawing anything on window surfaces.
So, one problem that I can think of: we need to init xvfb explicitly with the separate command to allow sharing its fake display among the workers.  The current `xvfb-run` method makes xvfb process child to the main command call (`worker`), therefore it'll exit when the worker exits and that shared display will be destroyed.

**Pull request merged**
