### PR TITLE
Initial new frontend rewrite

### PR DESCRIPTION
**Pull request by sergystepanov**
For review and fixes.

### CODE REVIEW

**Comment by giongto35** [comment]
Wow, I'm impressed by how much you put in to improve the frontend. Thank you so much. 
Sorry I forgot this, I'm focusing on preparing a blog post on this project. Is this PR completed, Can I start reviewing.

**Comment by sergystepanov** [comment]
No problem (: I hope it will be somewhat better to manage than before. Don't worry about PRs that much, they can wait, just focus on important stuff.
I was thinking to add some things before the reviewing (app/screen state, inputs as plugins) but, I think, it can be done in parallel. So, feel free to review it.
Add comments on all code/todos which you would like to change/(re-)implement and I'll try to do it.

One more thing, if this frontend is expected to be used in the future with the app as a base for new features, then, I afraid, there is no way around of standard Node+Webpack+EsLint+Tests+Vanilla JS/Framework path (WebAssembly as an alternative).

**Comment by giongto35** [comment]
Thank you so much. Standard JS with Node also good way to go.

I have some thing to finish by this Saturday. I will try to review this PR by this weekend.  (y)

**Comment by giongto35** [comment]
I just take a review. This is much much clearer. I really like this refactor, I always wish I could have some proper pub-sub, and you did it.
Are you ok if I set you contributor, so it is easier for you to make smaller merge? I'm confident with your change.
Btw, this is what I did for the last week: https://docs.google.com/presentation/d/1VFv8l2hVUINv2U36r7L11g4Oa_zVjHlr6MYymUbQXT4/ 
I can make it a blog post soon.

**Comment by sergystepanov** [comment]
Oh, wow! Anywhere I can watch your talk from the conference? And a blog post -- sounds great.

> Are you ok if I set you collaborator, so it is easier for you to make smaller merge? I'm confident with your change.

Cool. Sure. The lack of rights to make new branches is really painful (:. (and you should always test all changes)

**Comment by giongto35** [comment]
My presentation is just read the slide out :v, I have all my speaker note in the slide. I will try to make it a blog post soon.
Thank you very much again for your great contribution.

**Pull request merged**
