### PR TITLE
Use modified x264 lib

### PR DESCRIPTION
**Pull request by sergystepanov**
### x264 info
**Settings**

A list of useful settings extracted from the source [x264c](https://code.videolan.org/videolan/x264/-/blob/master/x264.c).

- `profile` Force the limits of an H.264 profile. Overrides all settings.
(baseline, main, high, ...)
```
for X264_CSP_I420 image encoding

   - baseline:
        --no-8x8dct --bframes 0 --no-cabac --cqm flat --weightp 0
        No interlaced.
        No lossless.
   - main:
        --no-8x8dct --cqm flat
        No lossless.
   - high:
        No lossless.
```
- `preset` Use a preset to select encoding settings [medium]. Overridden by user settings.
(ultrafast, superfast, veryfast, faster, fast, medium, slow, slower, veryslow, placebo)
```
    - ultrafast:
        --no-8x8dct --aq-mode 0 --b-adapt 0 --bframes 0 --no-cabac --no-deblock
        --no-mbtree --me dia --no-mixed-refs --partitions none --rc-lookahead 0 --ref 1
        --scenecut 0 --subme 0 --trellis 0 --no-weightb --weightp 0

    - superfast:
        --no-mbtree --me dia --no-mixed-refs --partitions i8x8,i4x4 --rc-lookahead 0
        --ref 1 --subme 1 --trellis 0 --weightp 1

    - veryfast:
        --no-mixed-refs --rc-lookahead 10 --ref 1 --subme 2 --trellis 0 --weightp 1

    - faster:
        --no-mixed-refs --rc-lookahead 20 --ref 2 --subme 4 --weightp 1

    - fast:
        --rc-lookahead 30 --ref 2 --subme 6 --weightp 1

    - medium (Default settings apply)
 
    - slow:
        --direct auto --rc-lookahead 50 --ref 5 --subme 8 --trellis 2

    - slower:
        --b-adapt 2 --direct auto --me umh --partitions all --rc-lookahead 60 --ref 8 --subme 9 --trellis 2

    - veryslow:
        --b-adapt 2 --bframes 8 --direct auto --me umh --merange 24 --partitions all --ref 16 
        --subme 10 --trellis 2 --rc-lookahead 60

     - placebo:
        --bframes 16 --b-adapt 2 --direct auto --slow-firstpass --no-fast-pskip
        --me tesa --merange 24 --partitions all --rc-lookahead 60 --ref 16 --subme 11 --trellis 2
```
- `tune` Tune the settings for a particular type of source or situation. Overridden by user settings. Multiple tunings are separated by commas. Only one psy tuning can be used at a time.
(psy tunings: film, animation, grain, stillimage, psnr, ssim / other tunings: fastdecode, zerolatency)
```
    - film (psy tuning):
        --deblock -1:-1 --psy-rd <unset>:0.15

    - animation (psy tuning):
        --bframes {+2} --deblock 1:1 --psy-rd 0.4:<unset> --aq-strength 0.6 --ref {Double if >1 else 1}

    - grain (psy tuning):
        --aq-strength 0.5 --no-dct-decimate --deadzone-inter 6 --deadzone-intra 6
        --deblock -2:-2 --ipratio 1.1--pbratio 1.1 --psy-rd <unset>:0.25 --qcomp 0.8

    - stillimage (psy tuning):
        --aq-strength 1.2 --deblock -3:-3 --psy-rd 2.0:0.7 

    - psnr (psy tuning):
        --aq-mode 0 --no-psy

    - ssim (psy tuning):
        --aq-mode 2 --no-psy

    - fastdecode:
        --no-cabac --no-deblock --no-weightb --weightp 0

    - zerolatency:
        --bframes 0 --force-cfr --no-mbtree --sync-lookahead 0 --sliced-threads --rc-lookahead 0
```

### Changes

- The old h264 encoder is rewritten in order to be able to make use of the external libx264 system library with SIMD instructions.
- Huge memory leaks are fixed.
- Added use of C YUV-converter.
- Added ability to change video codec and some (h264) config params in the settings file.

**Issues**

- It is possible that libx264 support in the app will be broken again after another API (C header) change by its authors.
- h264 encoder is harder to tweak for real-time encoding compared to more advanced and new vpx encoders.

### CODE REVIEW

**Comment by sergystepanov** [comment]
On small frames, h264 has color blocking which looks like shimmering.

feature006

**Comment by sergystepanov** [comment]
@giongto35, could you test it on an IOS? Successfully tested it on Android.
Since I don't know how to tweak it for low-res images (see the previous gif), I'll leave vp8 as the default video codec before the merge. Maybe, you know?

**Comment by giongto35** [comment]
Thanks Sergy, look like a lot of work has been done. I will try this branch on IOS soon. \:D/

**Comment by sergystepanov** [comment]
Cool. If it won't run for some reason try to set `baseline` profile and different presets.

**Comment by giongto35** [comment]
@sergystepanov just test with x264, it doesn't work on my local ubuntu  environment:
```
I0221 21:15:54.117190    1329 room.go:197] Viewport custom size is disabled, base size will be used instead 256x240
I0221 21:15:54.117229    1329 media.go:75] Video codec: h264
I0221 21:15:54.117304    1329 media.go:52] OPUS: Bitrate: 192000 bps, Complexity: 10, DTX: false, FEC: false, Max bandwidth: *1105, Loss%: 0, Rate: 48000 Hz
x264 [error]: invalid level_idc: 8
panic: x264: cannot open the encoder

goroutine 126 [running]:
github.com/giongto35/cloud-game/v2/pkg/encoder/h264.(*Encoder).init(0xc00038e400, 0xc00060de78, 0x1, 0x1, 0xc00060dd01, 0xc0005901e0)
        /home/thanh/Desktop/Code/cloud-game/pkg/encoder/h264/encoder.go:49 +0xf1
github.com/giongto35/cloud-game/v2/pkg/encoder/h264.NewEncoder(0x100, 0xf0, 0xc00060de78, 0x1, 0x1, 0xc0000e27b8, 0x8, 0x0, 0xc0005901e0)
        /home/thanh/Desktop/Code/cloud-game/pkg/encoder/h264/encoder.go:39 +0x167
github.com/giongto35/cloud-game/v2/pkg/worker/room.(*Room).startVideo(0xc000192180, 0x100, 0xf0, 0xc0000e2778, 0x4, 0x11, 0xc0000e27a0, 0x8, 0xc0000e27b8, 0x8, ...)
        /home/thanh/Desktop/Code/cloud-game/pkg/worker/room/media.go:77 +0x5c1
created by github.com/giongto35/cloud-game/v2/pkg/worker/room.NewRoom.func1
  /home/thanh/Desktop/Code/cloud-game/pkg/worker/room/room.go:214 +0x7da

```      
Setup
```
  video:
    # h264, vpx
    codec: h264
    # see: https://trac.ffmpeg.org/wiki/Encode/H.264
    h264:
      # Constant Rate Factor (CRF) 0-51 (default: 23)
      crf: 17
      # ultrafast, superfast, veryfast, faster, fast, medium, slow, slower, veryslow, placebo
      preset: veryfast
      # baseline, main, high, high10, high422, high444
      profile: baseline
      # film, animation, grain, stillimage, psnr, ssim, fastdecode, zerolatency
      tune: zerolatency
      # 0-3
      logLevel: 0
```

**Comment by sergystepanov** [comment]
@giongto35, which version of libx264 you have installed?

**Comment by sergystepanov** [comment]
Strange, on Ubuntas it probably has pretty old headers anyway. Wrong color profile index on 150, 160, dev. But it works for me.
image

Will look into the color problem.

**Comment by giongto35** [comment]
oh using docker it works, so it's problem with libx264 version on my machine. (How to check the version of libx264? `ffmpeg -h encoder=libx64` ?)
The color is wrong as well.
image

**Comment by sergystepanov** [comment]
It's strange. I mean, it's not strange. They really don't care about their lib compatibility, at some point, 3 years ago they just whack 4:0:0 monochrome color space before everything else with index 1 ([link](https://code.videolan.org/videolan/x264/-/blob/698c5a32e63a3ed6b976ed196abe479efd78530b/x264.h#L222)) and before that, it was our YUV color with that index. So the problem is, apart from really strange x264 lib versioning, on [ubuntu](https://packages.ubuntu.com/search?keywords=x264) we probably need the version 160-dev which is only in the new distros, there should be the proper x264.h header with the proper index. On older libs, it will be using YV12 colorspace.

**Comment by sergystepanov** [comment]
I'm checking installed like that:
```
apt list --installed | grep libx264
```

**Comment by sergystepanov** [comment]
@giongto35, I'll try to export x264_build constant in my wrapper and will set this color on condition if build less or more than v160. Then remove it sometime in the future.
Now, could you please check x264 on IOS?

**Comment by giongto35** [comment]
Nice work, work on IOS . Thanks Sergy
image

So now I wonder, is H264 better in term of performance for VPx now with hardware support?
`h264 encoder is harder to tweak for real-time encoding compared to more advanced and new vpx encoders.`
So which one should I make default now

**Comment by sergystepanov** [comment]
Cool, thanks!

You should probably reread the original topic #274. 
It's not hardware. It's software with CPU-optimizations.
In terms of performance and all I wrote that:
> For 1080p on my hardware, it's just 1 frame delay with h264 and 5 frames with vp8 codec.

It's much faster on that settings compared to your tweaked vp8 encoder.
But there is a problem with small resolutions, I haven't really tweaked it, tried some random settings but it didn't help (: Maybe, I'll come back to this later. And yes, it's present in your original encoder as well.
With x2 scale it looks great, without these artifacts but the performance hit is noticeable.

> Now the bad part. h264 is noticeably worse visually for encoding low-res frames in realtime compared to vpx codecs. Yes, it's faster but there are a lot of visual artifacts you have to deal with. Right now I have strange color shimmering on jumping Mario (Super Mario) and horizontal lines in Sushi The Cat (I'll add clips into the PR when have time). These artifacts are present in the old h264 encoder as well. No idea how to get rid of that yet.

**Comment by giongto35** [comment]
@sergystepanov 
Thanks very much for the nice detailed and explanation.
So even with x264 has less effective compression comparing to VP8, the frames speed is still faster right? 
In network scenario, better compression (lower size package) can help transmit faster. So I don't know if the speed of x264 is still faster than VPx in real network.

**Comment by sergystepanov** [comment]
> So even with x264 has less effective compression comparing to VP8, the frames speed is still faster right?

Yes. Keep in mind that between h264 and vp8 five years gap (I think). As you can imagine in this period of time several generations of CPU were released. h264 was designed for that specific period of time, for that generation of processors and media, as an effective future-proof video codec. Of course, it should be faster, it's like running Doom from the x386 era on a Pentium 4 with GeForce. Just raw CPU frequency would obliterate any ineffective or greedy algorithm. On top of that, since it's older and was pretty popular at the time, it's optimized quite well. At some point, x264 couldn't keep up with growing HD content demands and streaming services. For HD content it was not enough, slow and visually bad, so there was a faster alternative -- vpx codecs: vp8, vp9, av1. (I won't touch all that copyright and licensing wars, you can read about that in some wiki, that's not the point). So the main (technical) purpose of vpx codecs was HD streaming content. If you compare them head to head, for example, on 1080p encoding, then h264 will require more time and bitrate for a given quality baseline. For hardware (GPU) encoding, I can't tell and don't know what's better but I think at least vp8 should be not worse.
Given device support, h264 should be better pre-HD, and vpx should be better for HD, UHD.

> In network scenario, better compression (lower size package) can help transmit faster. So I don't know if the speed of x264 is still faster than VPx in real network.

You forgot about visual quality, it's a ratio between quality and size. I think, just test and see.

**Pull request merged**
