### PR TITLE
Add basic N64 support on Mac

### PR DESCRIPTION
**Pull request by 88hcsif**
Note: mupen64plus lib unload is not working properly on Mac, so stopping and restarting N64 emulation will cause a crash

### CODE REVIEW

**Comment by 88hcsif** [comment]
I am not sure why the CI tests are failing now...
If you point me in the right direction I can try to fix it.

**Comment by sergystepanov** [comment]
There is no coordinator package now, probably you've removed it by mistake

**Comment by 88hcsif** [comment]
Ah, yeah, I accidentally deleted a file...

**Comment by 88hcsif** [comment]
Okay, my branch is really screwed up I will just restart from scratch...

**Pull request closed without merging**
