### PR TITLE
Add initial support of portrait games

### PR DESCRIPTION
**Pull request by sergystepanov**
See #158.

Needs testing & code review.

### CODE REVIEW

**Comment by sergystepanov** [comment]
Funny thing that a call to the map `Angles[angle]` in a loop was a huge performance hit (:
Do you know why is that? Go maps are slow or something?

**Comment by giongto35** [comment]
@sergystepanov do you mean : pkg/emulator/libretro/image/rotation_test.go :179? How did you figure out the performance was hit because of that?

**Comment by sergystepanov** [comment]
I already fixed it.
I didn't expect that it will be so much expensive so the games started lagging (: a lot.
I mean that there was a call to the map inside [this double loop](https://github.com/giongto35/cloud-game/pull/186/files#diff-ab1eafce627bacd812e4f1b840d3e984R35-R48).

**Comment by sergystepanov** [comment]
Ah, I got what you mean (: Right, I think that's the problem. Thanks.
a := b

And for each assignment it did:
> That is, the assignment “f := MyFunc” would generate code like:
> MOV $MyFunc·f(SB), f1
> DATA MyFunc·f(SB)/8, $MyFunc(SB)
> GLOBL MyFunc·f(SB), 10, $8

In the current code it's being assigned only once per game start.

**Comment by sergystepanov** [comment]
```
goos: windows
goarch: amd64
pkg: github.com/giongto35/cloud-game/pkg/emulator/libretro/image
BenchmarkDirect
BenchmarkDirect-4      	1000000000	         0.916 ns/op
BenchmarkAssign
BenchmarkAssign-4      	305344443	         4.57 ns/op
BenchmarkMapDirect
BenchmarkMapDirect-4   	42606237	        27.0 ns/op
PASS
```

```go
func BenchmarkDirect(b *testing.B) {
	for i := 0; i < b.N; i++ {
		p1, p2 := Rotate90(1, 1, 2, 2)
		p1, p2 = p2, p1
	}
}


func BenchmarkAssign(b *testing.B) {
	fn := Angles[Angle90].Call
	for i := 0; i < b.N; i++ {
		p1, p2 := fn(1, 1, 2, 2)
		p1, p2 = p2, p1
	}
}

func BenchmarkMapDirect(b *testing.B) {
	for i := 0; i < b.N; i++ {
		p1, p2 := Angles[Angle90].Call(1, 1, 2, 2)
		p1, p2 = p2, p1
	}
}
```

**Comment by sergystepanov** [comment]
What the actual f***:
```
goos: windows
goarch: amd64
pkg: github.com/giongto35/cloud-game/pkg/emulator/libretro/image
BenchmarkCustomType
BenchmarkCustomType-4      	38711425	        26.2 ns/op
BenchmarkPrimitiveType
BenchmarkPrimitiveType-4   	136776249	         8.58 ns/op
PASS
```

```go
func BenchmarkCustomType(b *testing.B) {
	fns := map[Angle]func(x, y, w, h int) (int, int){
		Angle90: Rotate90,
	}

	for i := 0; i < b.N; i++ {
		p1, p2 := fns[Angle90](1, 1, 2, 2)
		p1, p2 = p2, p1
	}
}

func BenchmarkPrimitiveType(b *testing.B) {
	fns := map[uint]func(x, y, w, h int) (int, int){
		0: Rotate90,
	}

	for i := 0; i < b.N; i++ {
		p1, p2 := fns[0](1, 1, 2, 2)
		p1, p2 = p2, p1
	}
}
```

**Comment by giongto35** [comment]
OMG, this is so tricky. Thanks for the investigation.
Why the itoa affect the performance so much:/

**Comment by sergystepanov** [comment]
Oh, wow. This' because of uint8 key. Nice language...really like it.
```
goos: windows
goarch: amd64
pkg: github.com/giongto35/cloud-game/pkg/emulator/libretro/image
BenchmarkUintKey
BenchmarkUintKey-4    	129952644	         8.73 ns/op
BenchmarkUint8Key
BenchmarkUint8Key-4   	47733645	        25.8 ns/op
BenchmarkIntKey
BenchmarkIntKey-4     	139873735	         8.73 ns/op
PASS
```

```go
func BenchmarkUintKey(b *testing.B) {
	fns := map[uint]func(x, y, w, h int) (int, int){
		0: Rotate90,
	}

	for i := 0; i < b.N; i++ {
		p1, p2 := fns[0](1, 1, 2, 2)
		p1, p2 = p2, p1
	}
}

func BenchmarkUint8Key(b *testing.B) {
	fns := map[uint8]func(x, y, w, h int) (int, int){
		1: Rotate90,
	}

	for i := 0; i < b.N; i++ {
		p1, p2 := fns[1](1, 1, 2, 2)
		p1, p2 = p2, p1
	}
}

func BenchmarkIntKey(b *testing.B) {
	fns := map[int]func(x, y, w, h int) (int, int){
		1: Rotate90,
	}

	for i := 0; i < b.N; i++ {
		p1, p2 := fns[1](1, 1, 2, 2)
		p1, p2 = p2, p1
	}
}
```

**Comment by sergystepanov** [comment]
Added benchmarks. With uint key it's x3 faster but still x3 slower (: because of the map for some reason.

**Comment by sergystepanov** [comment]
Fixed with arrays (:/

**Comment by giongto35** [comment]
Im just wondering how should we interpret the benchmark. I think at ns level, these optimization like int -> uint can show significant impact but it might not be the real bottleneck.
For example, if an operation takes 24ns, we remove one line that cost 16ns, it reduces to 6ns and we think it is faster by 3 times, but in fact it just faster by 16 ns.
In the real run, the loop is like 60 fps, I think the game getting lagger overtime is due to some sort of memory piled up. 
Anyway, I will checkout and investigate the issue as well. : D Thank you so much for bringing this issue up.

**Comment by sergystepanov** [comment]
I'm not exactly sure what's your point (: with 16 ns or 3x faster, and you mean 8 ns? This op will be faster both: 3x and by 16 ns. If we'll use just this one operation one time as it's right now, that's doesn't matter at all. If we **have to** use this op inside a O(N) algo (as I did initially) or worse (because some algos can't have time complexity lower some upper bound even in a best case Ω) then there's no choice but either change your algo complexity and if you can't -- optimize operations inside.
Doing this bench, you can imagine how it would impact your performance isolated from everything else: 16ns x N. And in my case it was 320x240x1x32ns (1.5ms) then times it 60 fps.

In the real world you just look at ELK graphs of some main profiled code blocks or more likely just response times of your users and CPU/MEM utilization. If it's a trash you're profiling this on staging environment, then test fix, then ship to prod.

Now come to think about it: we have two separate data flows, one for video processing and one for audio processing. Audio processing is much-much faster than video. And I believe we don't have any king of AV synchronization. In that case if video takes more time for processing it's matter of time when it goes out of sync. This' exactly what I'm getting -- audio is being severe ahead of video especially when the OS scheduler pauses goroutines (app threads). Optimizing this video processing time should help but sadly -- not much. This issue is kinda critical, actually. (: But it needs some research. I'm lazy. (:

**Comment by sergystepanov** [comment]
Let's focus on the issue with portrait games (:
People are waiting. Performance wise it's alright -- rotation takes < 1% of time of the draw function.
Just check the code overal and if you have time -- test some portrait and your selection of ROMs for video artefacts. That would be great.

**Comment by giongto35** [comment]
I just ran your code bench and saw all the metrics look fine, then I realized it was after your change from array to map. Map is usually a bottleneck and it was an example in Go profile : https://blog.golang.org/pprof.
Overall, the code looks good to me : D Thank you very much for taking this change + nice investigation.

**Comment by sergystepanov** [comment]
Cool, thanks. Will read the docs. Next I'll finish settings module and then, maybe, try to understand [RTP Sync](https://github.com/runner365/read_book/blob/master/RTP_RTCP/RTP%EF%BC%9AAudio%20and%20video%20for%20the%20Internet.pdf). %)

**Pull request merged**
