### PR TITLE
Remove some PSX data

### PR DESCRIPTION
**Pull request by sergystepanov**
A quick fix for #130 with PCSX migration. Also, to properly remove all the sensitive data: [link](https://help.github.com/en/github/authenticating-to-github/removing-sensitive-data-from-a-repository).
Successfully tested on Windows:
```
[Log]: note: running with HLE BIOS, expect compatibility problems
```

### CODE REVIEW

**Comment by giongto35** [comment]
Wow, Thank you for this.
Let me check if it still working with my megaman rom first.

**Comment by giongto35** [comment]
PCSX_rearmed seems to run also, but the input doesn't work. I think you should add these bios together for pcsx rearmed also

> scph101.bin | Version 4.4 03/24/00 A | 6E3735FF4C7DC899EE98981385F6F3D0
> -- | -- | --
> scph7001.bin | Version 4.1 12/16/97 A | 1e68c231d0896b7eadcad1d7d8e76129
> scph5501.bin | Version 3.0 11/18/96 A | 490f666e1afb15b7362b406ed1cea246
> scph1001.bin | Version 2.0 05/07/95 A | dc2b9bf8da62ec93e868cfd29f0d067d

**Comment by sergystepanov** [comment]
> the input doesn't work

On which game? I'll try.

**Comment by giongto35** [comment]
I tried with Mega Man X4 and Harvest Moon Back to Nature. Can you check that.

**Comment by sergystepanov** [comment]
It seems to be working fine.
```
  library_name: PCSX-ReARMed
  library_version: r22 4b353f8
```
You are testing on Ubuntu, right?

Megaman
d
Harvestmoon
kkk

**Pull request merged**
